#!/usr/bin/env python
import optparse
import sys

optparser = optparse.OptionParser()
optparser.add_option("-i", "--input", dest="input", default="data/train.hyp1-hyp2-ref", help="Input file (default data/train.hyp1-hyp2-ref)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of hypothesis pairs to evaluate")
(opts, _) = optparser.parse_args()

input = [[sentence.strip().split() for sentence in pair.split(' ||| ')] for pair in open(opts.input)][:opts.num_sents]
for (n, (ref, h1, h2)) in enumerate(input):
  rset = set(ref)
  h1_match = h2_match = 0
  for w in h1:
    if w in rset: h1_match += 1
  for w in h2:
    if w in rset: h2_match += 1
  if h1_match > h2_match:
    print "1"
  elif h1_match == h2_match:
    print "0"
  else:
    print "-1"

