#!/bin/bash

git remote | grep upstream
if [ $? -ne 0 ] ; then
  git remote add upstream git@github.com:clab/sp2013.11-731.git
fi

git fetch upstream
if [ $? -ne 0 ] ; then
  echo Fetch command failed! 1>&2
  exit 1
fi

git merge upstream/master -m 'grab new assignments'

